canteen/urls.py
"""
The routing part of all the views.
"""


from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'canteen'
urlpatterns = [
    # The landing page
    path('', views.LandingView.as_view(), name='home'),
    
    # The menu page
    path('menu/', views.MenuView.as_view(), name='menu'),
    
    # The detail of the dish
    path('<int:pk>/', views.DishView.as_view(), name='not-api-dish-detail'),
    
    # The order form of the dish
    path('order/<int:dish>/', views.OrderView.as_view(), name='order'),
    
    # The thanking page when done ordering
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    
    # The page that tells ordering is not allowed
    path('invalid-order/', views.UnableToOrderView.as_view(), name='unable-to-order'),
    
    # The about page
    path('about/', views.AboutView.as_view(), name='about'),
    
    # The privacy policy page
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    
    # The feedback form
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    
    # The JSON report dictionary
    path('json-report/', views.json_report, name='json-report'),
    
    # The JSON customer's orders dictionary
    path('json-customer-orders/', views.json_customer_orders, name='json-customer-orders'),
    
    # The API for marking the order as ready
    path('api-mark-as-ready/<int:id>/',views.api_mark_order_ready,
         name='api-ready'),
    
    # The API for marking the order as served
    path('api-mark-as-served/<int:id>/',views.api_mark_order_served,
         name='api-served'),
    
    # The API for deleting an order
    path('api-delete-order/<int:id>/', views.api_delete_order,
         name='api-delete-order'),
    
    # The API for deleting a dish
    path('api-delete-dish/<int:id>/', views.api_delete_dish,
         name='api-delete-dish'),
    
    # The API for deleting a feedback
    path('api-delete-feedback/<int:id>/', views.api_delete_feedback,
         name='api-delete-feedback'),
    
    # The managing page of the dishes
    path('manage/dish/', views.ManageView.as_view(), name='manage-dishes'),

    # The form for creating the dish
    path('manage/dish/create/', views.CreateDishView.as_view(), name='create'),

    # The page for the realtime orders and others
    path('manage/orders/', views.RealTimeOrdersView.as_view(), name='orders'),
    
    # The form for updating an order
    path('manage/edit-order/<int:pk>/', views.UpdateOrderView.as_view(), name='edit-order'),
    
    # The form for updating a dish
    path('manage/edit/<int:pk>/', views.UpdateDishView.as_view(), name='edit'),
    
    # The login page
    path('login/', LoginView.as_view(
        template_name='canteen/login.html',
    )),
]

if settings.DEBUG:
     urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esticanteen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', include('canteen.urls')),
    path('admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

canteen/models.py
"""
Models for the `canteen`
"""

from django.db import models
from django.utils.timezone import datetime

from django_resized import ResizedImageField


# Signal-related imports
from django.db.models.signals import post_save
from django.db.models.signals import post_delete
from django.db import close_old_connections
from django.dispatch import receiver

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer


channel_layer = get_channel_layer()


class Dish(models.Model):
    """
    The Dish model.
    """
    name = models.CharField(max_length=50)
    price = models.FloatField()
    date = models.DateField()
    description = models.CharField(max_length=100)
    sold_out = models.BooleanField(default=False)
    everyday = models.BooleanField(default=False)
    photo = ResizedImageField(size=[400, 400], force_format='PNG')

    class Meta:
        verbose_name_plural = 'dishes'
        unique_together = ('name', 'date')

    def __str__(self):
        return self.name


class Feedback(models.Model):
    """
    The Feedback model.
    """
    date = models.DateTimeField(auto_now_add=True)
    contact_no = models.CharField(max_length=12)
    name = models.CharField(max_length=50)
    content = models.TextField()

    def __str__(self):
        return f'by {self.name}'


class Order(models.Model):
    """
    The order model.
    """
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=50)
    id_no = models.CharField('id no.', max_length=20)
    contact_no = models.CharField(max_length=12)
    dish = models.ForeignKey(Dish, related_name='orders', on_delete=models.CASCADE)
    count = models.IntegerField(default=1)
    served = models.BooleanField(default=False)
    ready = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} orderred {self.dish}'


# Signal-related functions


def send():
    async_to_sync(channel_layer.group_send)(
        "report", {
            "type": "report",
            'message': ''
        }
    )


@receiver(post_save, sender=Order)
def notify_report(sender, **kwargs):
    send()


@receiver(post_save, sender=Dish)
def notify_dish(sender, **kwargs):
    send()


@receiver(post_delete, sender=Order)
def notify_report_on_delete(sender, **kwargs):
    send()


@receiver(post_save, sender=Feedback)
def notify_feedbacks(sender, **kwargs):
    send()

canteen/forms.py
"""
Forms for `canteen`
"""


from django import forms
from django.utils.timezone import datetime
from django.db.models import Q

from .models import Dish
from .models import Order
from .models import Feedback


class OrderForm(forms.ModelForm):
    contact_no = forms.CharField(min_length=11)
    count = forms.IntegerField(min_value=1, initial=1)

    class Meta:
        model = Order
        fields = ['name', 'id_no', 'contact_no', 'count']


class FeedbackForm(forms.ModelForm):
    contact_no = forms.CharField(min_length=11)

    class Meta:
        model = Feedback
        fields = ['name', 'contact_no', 'content']


class UpdateOrderForm(forms.ModelForm):
    dish = forms.ModelChoiceField(queryset=None)
    contact_no = forms.CharField(min_length=11)

    def __init__(self, *args, **kwargs):
        super().__init__( * args, ** kwargs)
        # Get the dishes
        self.fields['dish'].queryset = Dish.objects.filter(
            Q(date=self.instance.date) | Q(everyday=True))

    class Meta:
        model = Order
        fields = ['name', 'id_no', 'contact_no', 'count', 'dish']

canteen/views.py
"""
Views for the `canteen`
"""

from django.dispatch import receiver
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.utils.timezone import datetime
from django.utils.datastructures import MultiValueDictKeyError
from django.http import JsonResponse
from django.http import HttpResponseForbidden
from django.http.response import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.core.signals import request_started
from django.core.signals import request_finished
from django.db.models import Sum
from django.db.models import Q
from django.db import close_old_connections

from .models import Dish
from .models import Order
from .models import Feedback
from .forms import UpdateOrderForm
from .forms import OrderForm
from .forms import FeedbackForm


def get_orders(request):
    """
    Utility function for getting orders.
    """
    close_old_connections()
    try:
        # Give all orders maded on the given date.
        return Order.objects.filter(
            date__date=request.GET['date']).order_by('-date')
    except MultiValueDictKeyError:
        # Give all orders today.
        return Order.objects.filter(
            date__date=datetime.now().date()).order_by('-date')


@receiver(request_started)
def started_request(**kwargs):
    close_old_connections()


@receiver(request_finished)
def finished_request(**kwargs):
    close_old_connections()


class LandingView(TemplateView):
    """
    View for the landing page of the website.
    """
    template_name = 'canteen/index.html'

    def dispatch(self, request, *args, **kwargs):
        
        close_old_connections()
        
        # get the orders
        orders_today = get_orders(request)
        
        for o in request.session.get('orders', []):
            # remove the pk of the order if it does not exist
            if not Order.objects.filter(id=o).exists():
                self.request.session.get('orders').remove(o)
                self.request.session['orders'] = (
                    self.request.session.get('orders'))
        
        return super().dispatch(request, *args, **kwargs)


class MenuView(ListView):
    """
    View for listing the dishes.
    """
    context_object_name = 'dishes'

    def get_context_data(self, **kwargs):
        close_old_connections()
        context = super().get_context_data(**kwargs)
        
        # get the sum of all orders today
        context['orders_count'] = Order.objects.filter(
            date__date=datetime.now().date()
            ).aggregate(Sum('count'))['count__sum']
        
        return context

    def get_queryset(self):
        close_old_connections()

        # order it by name
        return Dish.objects.filter(
            Q(date=datetime.now()) | Q(everyday=True)
        ).order_by('name')


class AboutView(TemplateView):
    """
    View for simply displaying the about page.
    """
    template_name = 'canteen/about.html'


class PrivacyPolicyView(TemplateView):
    """
    View for simply displaying the privacy policy.
    """
    template_name = 'canteen/privacypolicy.html'


class DishView(DetailView):
    """
    View for displaying the dish's detail.
    """
    model = Dish

    def get_context_data(self, **kwargs):
        close_old_connections()
        context = super().get_context_data(**kwargs)
        
        # get the sum of all orders of this dish
        context['orders'] = Order.objects.filter(
            dish=self.object).aggregate(Sum('count'))['count__sum']
        
        return context


class OrderView(CreateView):
    """
    View for creating orders.
    """
    form_class = OrderForm
    template_name = 'canteen/order_form.html'
    success_url = reverse_lazy('canteen:thanks')

    def dispatch(self, request, *args, **kwargs):
        close_old_connections()

        # get the dish based from the pk
        self.dish = Dish.objects.get(id=kwargs['dish'])
        
        # redirect if ordering is not allowed
        if self.dish.sold_out:
            return HttpResponseRedirect(reverse_lazy('canteen:unable-to-order'))
        
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # assign the dish
        form.instance.dish = self.dish
        
        # upper the name
        form.instance.name = form.instance.name.upper()
        
        # save it now
        form.save()

        # create the orders holder in the session
        if type(self.request.session.get('orders')) != list:
            self.request.session['orders'] = []
        
        # get the orders from the session and add the new pk
        orders = self.request.session.get('orders')
        orders.append(form.instance.id)
        
        # assign the order again
        self.request.session['orders'] = orders

        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        close_old_connections()
        context = super().get_context_data(**kwargs)
        
        # add the chosen dish in the context
        context['dish'] = self.dish
        
        return context


class UnableToOrderView(TemplateView):
    """
    View for informing the customer that the order can't be allowed.
    """
    template_name = 'canteen/unable_to_order.html'


class FeedbackView(CreateView):
    """
    View for creating a feedback.
    """
    form_class = FeedbackForm
    success_url = reverse_lazy('canteen:home')
    template_name = 'canteen/feedback_form.html'

    def form_valid(self, form):
        # upper the name
        form.instance.name = form.instance.name.upper()
        return super().form_valid(form)


class ThanksView(TemplateView):
    """
    View for simply thanking the customer.
    """
    template_name = 'canteen/thanks.html'


class RealTimeOrdersView(LoginRequiredMixin, TemplateView):
    """
    View for displaying the template for orders and report.
    """
    login_url = '/login/'
    redirect_field_name = 'next'
    template_name = 'canteen/real_time_orders.html'


class ManageView(LoginRequiredMixin, ListView):
    """
    Home view of the managing site.
    """
    login_url = '/login/'
    template_name = 'canteen/manage.html'
    context_object_name = 'dishes'

    def get_queryset(self):
        close_old_connections()
        try:
            # Give the dishes that were created on the given date
            # and are not for everyday.
            return Dish.objects.filter(
                date=self.request.GET['date'],
                everyday=False
            ).order_by('name')
        except MultiValueDictKeyError:
            # Give the dishes that were created today and are not
            # for everyday.
            return Dish.objects.filter(
                date=datetime.now(),
                everyday=False
            ).order_by('name')
    
    def get_context_data(self, **kwargs):
        close_old_connections()
        context = super().get_context_data(**kwargs)
        
        # add the everyday dishes
        context['everyday_dishes'] = Dish.objects.filter(
            everyday=True).order_by('name')
        
        return context


class CreateDishView(LoginRequiredMixin, CreateView):
    """
    View for creating a dish.
    """
    login_url = '/login/'
    model = Dish
    fields = ['name', 'price', 'description', 'photo', 'everyday']
    success_url = reverse_lazy('canteen:manage-dishes')
    template_name = 'canteen/create_dish.html'

    def form_valid(self, form):
        # Uppercase the name.
        form.instance.name = form.instance.name.upper()
        # Set the date.
        form.instance.date = datetime.now().date()
        return super().form_valid(form)


class UpdateDishView(LoginRequiredMixin, UpdateView):
    """
    View for updating a dish.
    """
    login_url = '/login/'
    success_url = reverse_lazy('canteen:manage-dishes')
    model = Dish
    fields = ['name', 'price', 'description', 'sold_out', 'photo',
              'everyday', 'date']
    template_name = 'canteen/edit_dish.html'

    def form_valid(self, form):
        # Uppercase the name.
        form.instance.name = form.instance.name.upper()
        # Set the date.
        form.instance.date = datetime.now().date()
        return super().form_valid(form)


class UpdateOrderView(LoginRequiredMixin, UpdateView):
    """
    View for updating an order.
    """
    login_url = '/login/'
    success_url = reverse_lazy('canteen:orders')
    form_class = UpdateOrderForm
    model = Order
    template_name = 'canteen/edit_order.html'

    def form_valid(self, form):
        # Uppercase the name.
        form.instance.name = form.instance.name.upper()
        # Set the date.
        form.instance.date = datetime.now().date()
        return super().form_valid(form)


def json_report(request):
    """
    View for giving the report.
    """

    close_old_connections()

    # Not allow unauthenticated users.
    if not request.user.is_authenticated:
        return HttpResponseForbidden("You're not authenticated.")
    
    # Get orders.
    orders = get_orders(request)

    # Form the audit.
    audit = {
        'total_orders_amount': 0,
        'total_orders_served_amount': 0
    }
    for order in orders:
        amount = order.count * order.dish.price
        if order.served:
            audit['total_orders_served_amount'] += amount
        audit['total_orders_amount'] += amount
    audit['total_amount_still_out'] = (
            audit['total_orders_amount'] - audit['total_orders_served_amount'])
    
    # Form the orders.
    orders = [
        {
            'id': order.id,
            'name': order.name,

canteen/templates/canteen/dish-list.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'canteen/w3.css' %}" />
    <style>
        html,
        body {
            height: 100%;
            padding: 0px;
            margin: 0px;
        }

        header {
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        header h1 {
            font-size: 50px;
        }

        .dish {
            padding-left: 5px;
            padding-right: 5px;
            padding-bottom: 30px;
        }

        .dish-image {
            width: 100%;
            height: 300px;
        }

        .sold-out {
            opacity: 0.5;
        }

        @media only screen and (min-width: 600px) {
            header h1 {
                font-size: 70px;
            }
        }

        @media only screen and (min-width: 768px) {
            header h1 {
                font-size: 90px;
            }
        }
    </style>
</head>

<body>
    <header class="w3-purple">
        <div class="w3-container w3-center">
            <h1>Welcome to ESTI Canteen!</h1>
            <h4 class="w3-opacity">It's so good to eat, especially if you paid well.</h4>
        </div>
    </header>

    <article class="w3-container w3-padding-32 w3-margin">
        <div class="w3-content">
            <h2>Our menu for today!</h2>
            <div class="w3-row">
                {% for dish in dishes %}
                <a href="{% url 'canteen:dish-detail' dish.id %}">
                    <div class="w3-col m6 l4 dish {% if dish.sold_out %}sold-out{% endif %}">
                        <div class="w3-center w3-card-4 w3-border w3-border-purple w3-bottombar w3-round">
                            <div class="dish-image w3-purple"></div>
                            <div class="w3-padding">
                                <h4 class="{% if dish.sold_out %}w3-text-red{% endif %}">
                                    {{ dish.name }}
                                </h4>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </article>
</body>

</html>

canteen/templates/canteen/dish_detail.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html>

<head>
    <title>ESTI Canteen - {{ dish.name|title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <meta name="og:title" content="ESTI Canteen - {{ dish.name|title }}" />
    <meta name="twitter:title" content="ESTI Canteen - {{ dish.name|title }}" />
    <meta name="description" content="{{ dish.description }}" />
    <meta name="twitter:description" content="{{ dish.description }}" />
    <meta name="og:description" content="{{ dish.description }}" />
    <meta name="twitter:image" content="{{ dish.photo.url }}" />
    <meta name="og:image" content="{{ dish.photo.url }}" />

    <link rel="icon" href="{% static 'canteen/esti_icon.png' %}" type="image/x-icon" />
    <script rel="script" src="{% static 'canteen/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'canteen/w3.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <style>
        @import url(https://fonts.googleapis.com/css?family=Sofia);

        html,
        body {
            height: 100%;
            width: 100%;
            padding: 0px;
            margin: 0px;
            background: url("{% static 'canteen/detail-bg.jpg' %}");
        }

        body>div:first-child {
            height: 100%;
            width: 100%;
            display: flex;
        }

        body>div:first-child>div {
            height: 100%;
            width: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        img {
            width: 100%;
            height: 100%;
            object-fit: cover;
            border: 3px solid white;
            border-radius: 20px;
        }

        #dish-image {
            flex-grow: 6;
            padding: 10px;
        }

        #edit-link {
            top: 16px;
            left: 16px;
            display: flex;
        }

        #edit-link,
        #view-toggle {
            position: absolute;
            width: 40px;
            height: 40px;
            border-radius: 100%;
            justify-content: center;
            align-items: center;
        }

        #view-toggle {
            top: 32px;
            right: 32px;
            display: none;
            z-index: 1;
        }

        #dish-details {
            flex-direction: column;
            text-align: center;
            overflow-y: auto;
            color: white;
            position: relative;
        }

        .w3-button {
            margin-top: 3px;
            margin-bottom: 3px;
        }

        body>div:first-child h1 {
            font-family: 'Sofia';
            font-weight: 800;
        }

        .standout {
            background: rgba(128, 128, 128, 0.438);
            border-radius: 10px;
            padding: 10px;
            border: 1px dashed white;
        }

        @media only screen and (min-width: 600px) {
            body>div:first-child h1 {
                font-size: 50px;
            }
        }

        @media only screen and (min-width: 768px) {
            body>div:first-child h1 {
                font-size: 70px;
            }
        }

        @media only screen and (max-width: 767px) {
            body {
                border: none;
            }

            body>div:first-child {
                flex-direction: column;
                padding: 16px;
            }

            #edit-link,
            #view-toggle {
                background: white;
                border: 1.5px solid black;
                color: black;
                display: flex;
            }

            .standout {
                background: rgba(128, 128, 128, 0.836)
            }

            #dish-image {
                display: none;
            }

            #dish-details {
                background: url("{{ dish.photo.url }}") no-repeat center fixed;
                background-size: cover;
                border: 3px solid white;
                border-radius: 32px;
                box-shadow: 0 4px 10px 0 rgba(0, 0, 0, 0.2), 0 4px 20px 0 rgba(0, 0, 0, 0.19)
            }
        }
    </style>
</head>

<body class="w3-animate-opacity">
    <div>
        <div id="dish-image" class="w3-animate-top">
            <img src="{{ dish.photo.url }}">
        </div>
        <button id="view-toggle" class="w3-button"><i class="fas fa-eye-slash"></i></button>
        <div id="dish-details" class="w3-animate-zoom">
            {% if user.is_authenticated %}
            <a id="edit-link" href="{% url 'canteen:edit' dish.id %}" class="w3-button"><i
                    class="fas fa-pencil-alt"></i></a>
            {% endif %}
            <div class="w3-container" id="dish-very-details">
                <h1 style="margin:0px"><i class="w3-text-red fas fa-heart"></i></h1>
                <h1 style="margin-top:0px" class="standout">{{ dish.name|title }}</h1>
                {% if dish.sold_out %}
                <p class="w3-large w3-tag w3-round w3-red">SOLD OUT</p>
                <p class="w3-large standout">Sad. You did not come early.</p>
                <div class="w3-margin-top">
                    <a href="{% url 'canteen:menu' %}#article" class="w3-button w3-round-xxlarge w3-purple"><i
                            class="fas fa-list"></i> Menu</a>
                    <a href="{% url 'canteen:feedback' %}" class="w3-button w3-round-xxlarge w3-purple">
                        <i class="fas fa-feather-alt"></i> Feedback</a>
                </div>
                {% else %}
                <p class="w3-margin-bottom w3-large standout">
                    It costs <span class="w3-tag w3-light-green w3-round-xxlarge">₱ {{ dish.price|intcomma }}</span>.
                    {{ dish.description }}
                    {% if not orders %}
                    No one is ordering it yet. Be the first to order!
                    {% elif orders == 1 %}
                    It has already {{ orders|intcomma }}
                    order, as of now.
                    {% else %}
                    It has already {{ orders|intcomma }}
                    orders, as of now.
                    {% endif %}
                </p>
                <div class="w3-margin-top">
                    <a href="{% url 'canteen:menu' %}#article" class="w3-button w3-round-xxlarge w3-purple">
                        <i class="fas fa-list"></i> Menu</a>
                    <a href="{% url 'canteen:feedback' %}" class="w3-button w3-round-xxlarge w3-purple">
                        <i class="fas fa-feather-alt"></i> Feedback</a>
                    <a href="{% url 'canteen:order' dish.id %}" class="w3-button w3-round-xxlarge w3-purple">
                        <i class="fas fa-check-circle"></i> Order</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% include 'canteen/footer.html' with canShare=True %}

    <script>
        $(document).ready(function () {
            var toggle = 1;
            $('#view-toggle').click(function () {
                if (toggle) {
                    $(this).html('<i class="fas fa-eye"></i>');
                    $('#dish-very-details').fadeOut();
                    toggle = 0;
                } else {
                    $(this).html('<i class="fas fa-eye-slash"></i>');
                    $('#dish-very-details').fadeIn();
                    toggle = 1;
                }
            });
        })
    </script>
</body>

</html>

canteen/templates/canteen/nav.html
{% load static %}


<style>
    @import url(https://fonts.googleapis.com/css?family=Sofia);

    .nav-cont {
        width: 100%;
        position: fixed;
        display: flex;
        flex-direction: row;
        justify-content: center;
        z-index: 2;
        transition: 0.3s;
    }

    .navigation {
        display: flex;
        flex-direction: row;
        width: 100%;
        max-width: 980px;
        padding: 8px;
    }

    .nav-cont .brand {
        flex-grow: 1;
        font-family: 'Sofia';
        font-weight: 800;
        font-size: 25px;
        display: flex;
        flex-direction: row;
        align-items: center;
    }

    .navigation .brand img {
        margin-right: 10px;
    }

    .navigation .brand a {
        text-decoration: none;
        display: flex;
        flex-direction: row;
        align-items: center;
        background: rgba(255, 255, 255, 0.521);
        border-radius: 32px;
        padding: 0px 16px 0px 16px;
    }

    .navigation .links {
        display: flex;
        flex-direction: row;
        justify-content: flex-end;
        align-items: center;
        flex-grow: 2;
    }

    .navigation .links a {
        display: flex;
        align-items: center;
        text-decoration: none;
        height: 100%;
        padding: 0px 16px 0px 16px;
        margin: 0px 5px 0px 5px;
        border-radius: 32px;
        background: rgba(255, 255, 255, 0.521);
    }

    .navigation .links i {
        padding-right: 5px;
    }

    .scrolled {
        background: white !important;
    }

    .scrolled .links a {
        background: #9e9e9e3b;
    }

    #menu-btn {
        display: none;
        position: fixed;
        top: 0px;
        right: 0px;
        margin: 8px;
        height: 37px;
        width: 37px;
        border-radius: 100%;
        border: none;
        background: rgba(255, 255, 255, 0.521);
        color: black !important;
        z-index: 3;
    }

    #menu-btn:hover {
        background: #f1f1f1;
    }

    @media (max-width: 800px) {
        /* NAV Media */

        #menu-btn {
            display: block;
        }

        .navigation {
            flex-direction: column;
            padding: 0px;
        }

        .navigation .brand {
            padding: 8px;
        }

        .navigation .links {
            display: none;
        }

        .navigation .links a {
            display: block;
            align-items: center;
            text-decoration: none;
            padding: 10px 16px 10px 32px;
            margin: unset !important;
            border-radius: 0px !important;
            background: white !important;
        }

        .navigation .links a:hover {
            background: #f1f1f1 !important;
        }
    }
</style>

<button id="menu-btn"><i class="fa fa-bars"></i></button>
<div class="nav-cont">
    <nav class="navigation">
        <div class="brand"><a href="{% url 'canteen:home' %}"><img src="{% static 'canteen/esti_icon.png' %}" width="25"
                    height="auto"> ESTI Canteen</a>
        </div>
        <div class="links">
            <a href="{% url 'canteen:menu' %}"><i class="fas fa-list"></i> Menu</a>
            <a href="{% url 'canteen:feedback' %}"><i class="fas fa-feather-alt"></i> Feedback</a>
            <a href="{% url 'canteen:privacy-policy' %}"><i class="fas fa-cookie"></i> Privacy Policy</a>
            <a href="{% url 'canteen:about' %}"><i class="fas fa-info-circle"></i> About</a>
        </div>
    </nav>
</div>

<script>
    var toggleMenu = 1;
    $(document).ready(function () {
        var nav = $(".nav-cont");
        var navLinks = $('.navigation .links');
        var menuBtn = $('#menu-btn');
        nav.toggleClass('scrolled', $(this).scrollTop() > nav.height());
        $(document).scroll(function () {
            nav.toggleClass('scrolled', $(this).scrollTop() > nav.height() || toggleMenu === 0);
            nav.toggleClass('w3-card-4', $(this).scrollTop() > nav.height() || toggleMenu === 0);
        });
        menuBtn.click(function () {
            if (toggleMenu === 1) {
                navLinks.slideDown();
                nav.addClass('scrolled');
                nav.addClass('w3-card-4');
                $(this).html('<i class="fa fa-times"></i>');
                toggleMenu = 0;
            } else {
                navLinks.slideUp();
                if ($(this).scrollTop() > nav.height()) {
                    nav.removeClass('scrolled');
                    nav.removeClass('w3-card-4');
                }
                $(this).html('<i class="fa fa-bars"></i>');
                toggleMenu = 1;
            }
        });
    })
</script>